"$schema" = 'https://starship.rs/config-schema.json'

palette = 'malcak'

# os symbols are mainly from nf-linux-*
# hostname, username, directory, time, duration symbols are from nf-oct-*
# git symbols are primarily from nf-cod-*
# programming languages are primarily from nf-md-language-*, nf-dev-*
# other symbols are from nf-dev-*

format = """
$os\
$username\
$hostname\
$directory\
$time\
$cmd_duration\
([ ](black)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$kubernetes\
$helm\
$all)\
$line_break\
[ │](fg:black)\
$line_break\
[ ╰─](fg:black)\
$character
"""

command_timeout = 1500
add_newline = true

[palettes.malcak]
black = '#404040'
red = '#e06c75'
green = '#98c379'
yellow = '#e5c07b'
blue = '#61afef'
purple = '#c678dd'
cyan = '#56b6c2'
white = '#fafafa'
orange = '#fe8019'
bright-black = '#2d2d2d'
bright-red = '#e45649'
bright-green = '#50a14f'
bright-yellow = '#c18401'
bright-blue = '#0184bc'
bright-purple = '#a626a4'
bright-cyan = '#0997b3'
bright-white = '#8c8c8c'
bright-orange = '#af3a03'

icon_bg = '#404040'
icon_fg = '#8c8c8c'
text_bg = '#2d2d2d'
text_fg = '#fafafa'

sep = '#363636'

[os]
symbols = { Debian = "", Fedora = "", Macos = "", Raspbian = "", Unknown = "?", Windows = "" }
style = "bg:icon_bg fg:text_fg"
format = '[ $symbol ]($style)[ $name ](bg:text_bg fg:text_fg) '
# format = '[ @ ]($style)'
disabled = true

[hostname]
ssh_only = true
ssh_symbol = ""
style = "bg:text_bg fg:text_fg"
format = "[ $ssh_symbol ](bg:icon_bg fg:cyan)[ $hostname ](bg:icon_bg fg:cyan bold inverted) "

[username]
show_always = true
style_user = "bg:text_bg fg:text_fg"
format = '[ @ ]($style bg:icon_bg)[ $user ]($style fg:bright-white) '
# format = '[  ]($style bg:icon_bg)[ $user ]($style fg:bright-white) '
# format = '[ $user ]($style fg:bright-white) '
disabled = false

[directory]
style = "bg:text_bg fg:text_fg"
format = "[  ](bg:icon_bg fg:yellow)[ $path ]($style fg:bright-white) "
truncation_length = 3
truncation_symbol = "…/"

[time]
disabled = false
time_format = "%R"
style = "bg:text_bg fg:text_fg"
format = '[  ]($style bg:icon_bg)[ $time ]($style fg:bright-white) '

[cmd_duration]
min_time = 500
show_milliseconds = true
style = "bg:text_bg fg:text_fg"
format = '[  ]($style bg:icon_bg)[ $duration ]($style fg:bright-white) '

[character]
error_symbol = "[▶](red)"
success_symbol = "[▶](black)"

[git_branch]
symbol = ""
style = "bg:text_bg fg:text_fg"
format = '[ $symbol ](bg:icon_bg fg:red)[ $branch ]($style) '

[git_status]
style = "bg:text_bg fg:text_fg"
format = '([  ](bg:icon_bg fg:red)[ $all_status$ahead_behind ]($style) )'
conflicted = ""
ahead = ">"
behind = "<"
diverged = "<>"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "r"
deleted = "x"

[git_state]
style = "bg:text_bg fg:text_fg"
format = '([  ](bg:icon_bg fg:red)[ $state($progress_current/$progress_total) ]($style) )'

[terraform]
symbol = "󱁢"
style = "bg:text_bg fg:text_fg"
format = '[ $symbol ](bg:icon_bg fg:purple)[( $version )]($style)([ $workspace ](bg:icon_bg fg:purple bold inverted)) '

[python]
symbol = "󰌠"
style = "bg:text_bg fg:text_fg"
format = '[ $symbol ](bg:icon_bg fg:green)[( $version )]($style)([ $virtualenv ](bg:icon_bg fg:green bold inverted)) '

[rust]
symbol = ""
style = "bg:text_bg fg:text_fg"
format = '[ $symbol ](bg:icon_bg fg:orange)[( $version )]($style) '

[lua]
symbol = "󰢱"
style = "bg:text_bg fg:text_fg"
format = '[ $symbol ](bg:icon_bg fg:blue)[( $version )]($style) '

[golang]
# symbol from nf-seti-go
symbol = ""
style = "bg:text_bg fg:text_fg"
format = '[ $symbol ](bg:icon_bg fg:blue)[( $version )]($style) '

[ruby]
symbol = "󰴭"
style = "bg:text_bg fg:text_fg"
format = '[ $symbol ](bg:icon_bg fg:red)[( $version )]($style) '

[java]
symbol = "󰬷"
style = "bg:text_bg fg:text_fg"
format = '[ $symbol ](bg:icon_bg fg:red)[( $version )]($style) '

[zig]
symbol = ""
style = "bg:text_bg fg:text_fg"
format = '[ $symbol ](bg:icon_bg fg:yellow)[( $version )]($style) '

[kubernetes]
detect_files = ['helmfile.yaml', 'Chart.yaml', 'chart.yaml', 'config']
symbol = ""
style = "bg:text_bg fg:text_fg"
format = '[ $symbol ](bg:icon_bg fg:blue)[( $context )]($style)([ $namespace ](bg:icon_bg fg:blue bold inverted)) '
disabled = false

[helm]
detect_files = ['helmfile.yaml', 'Chart.yaml', 'chart.yaml', 'config']
symbol = ""
style = "bg:text_bg fg:text_fg"
format = '[ $symbol ](bg:icon_bg fg:bright-blue)[( $version )]($style) '
disabled = false

[package]
disabled = true

[docker_context]
disabled = true

[vagrant]
disabled = true

[nodejs]
disabled = true

[bun]
disabled = true

[deno]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true
